### ISSUE TITLE
Pause/Resume not working

### ISSUE THREAD

**Issue by zenlex** [bitfocus/companion-module-showcuesystems-scs#1]
Stop all, go, prev q, next q, and go to top of cue list all tested and working but the pause/resume cue and pause/resume all don't seem to be functioning properly - they don't trigger proper responses in SCS (or any response at all other than the message was recieved)

**Comment by zenlex** [comment]
I don't see any discrepancies between what I would have expected in the code and the SCS OSC documentation so I'm baffled....

**Comment by josephdadams** [comment]
The `pauseall` has been fixed in latest.
