### ISSUE TITLE
Fade ALL Button function missing. 

### ISSUE THREAD

**Issue by nastasec89** [bitfocus/companion-module-showcuesystems-scs#2]
The Fade ALL Button function it's missing. It is one of the most important function when running strings for awards shows.

**Comment by jensorium** [comment]
Hey, this works with OSC:

SCS:
cue control network in SCS is a network server

Companion
Generic OSC
IP and port like SCS
send message without arguments, path /ctrl/fadeall

hope this helps!

**Comment by uhinkel** [comment]
Fadeall ist a function that does not exist on the SCS-surface. If you want to fade out all playing Cues you have to create a SFR (Stop/Fade/Release)-Cue. Then you can run this cue via OSC-Command to fade out all cues.
