### ISSUE TITLE
Can get Stream Deck with Companion on pi to control SCS

### ISSUE THREAD

**Issue by TomEagle** [bitfocus/companion-module-showcuesystems-scs#3]
Can you help me with this problem. I am not sure where to look.
Thanks,
Tom Eagle

**Comment by TomEagle** [comment]
I found the problem.... now how do we get it corrected?
Companion uses "/scs/ctrl/goto, s Q001" while SCS is  expecting "/scs/crtl/gotocue, s Q001"
Thanks,

Title should of been "Can't get Stream Deck with Companion on pi to control SCS (Show Cue System)"

**Comment by josephdadams** [comment]
Fixed this for you in the betas my friend. Have a good night!
