### ISSUE TITLE
While viewing the code I found two more problems

### ISSUE THREAD

**Issue by TomEagle** [bitfocus/companion-module-showcuesystems-scs#4]
I found a couple of problems with this module.
In index.js at line 158:
'pause' should be 'pauseall' because the action at line 212 has 'pauseall'

In index.js at line 159:
there is no corresponding  'stop' action in instance.prototype.action function

I am going to see if Mike can return a status of which Cue is active/next. Maybe that feature can be added to Companion to light up the corresponding button. I think Mike already does the Return A Status to the cellphone app.

Joseph Adams, Thanks for looking and fixing. I also sent this message to per.roine@gmail.com earlier

**Comment by TomEagle** [comment]
I am not familiar with getting the beta version.

**Comment by josephdadams** [comment]
Hello, I fixed the `pauseall` and commented out the `stop`.
