### ISSUE TITLE
Qualified against Companion 3.1

### ISSUE THREAD

**Issue by PhilVale** [bitfocus/companion-module-showcuesystems-scs#6]
OK so it seems to work but is there a plan to bring this module upto date to qualify it against Companion 3.1?

**Comment by bperryrm** [comment]
I'm trying to load it on Companion 3.1.2+6243-stable and it's not working (or I've made a configuration error), any chance it's working on the beta or other release without me having to load them?

**Comment by PhilVale** [comment]
I've certainly had it working on 3.1.2 but only limited due to it's lack of being qualified against these latest levels, so Go & Stop work.

I THINK I've also had it working again 3.2.2 Beta's but once again only a limited usage due to lack of it being qualified against these laatest levels. I can't afford for it to not work when I'm in the middle of a show.

**Comment by josephdadams** [comment]
module is upgraded to v3 API now so let me know if you have any trouble by opening a new issue

**Comment by PhilVale** [comment]
Thanks Joseph, I can confirm that having downloaded last nights Beta Build has no longer has the warning triangle against it.
